version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hqXzNv2f5YC45veW

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hqXzNv2f5YC45veW

  refract-cms: 
    build: ./refract-cms
    environment: 
      MONGO_URI: mongodb://root:hqXzNv2f5YC45veW@mongo:27017/refract-cms?authSource=admin
    ports:
      - "3000:3000"
      