apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: refract-cms-{{ .Values.env }}
  namespace: '{{ .Release.Namespace }}'
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: refract-cms-{{ .Values.env }}.alexbechmann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80
    - host: www.refract-cms.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80
  tls:
    - hosts:
        - www.refract-cms.com
      secretName: www.refract-cms.com-tls
    - hosts:
        - refract-cms-{{ .Values.env }}.alexbechmann.dev
      secretName: refract-cms-{{ .Values.env }}.alexbechmann.dev-tls
