apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: '{{ .Values.dockerUsername }}/refract-cms-website:{{ .Values.tag }}'
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
          ports:
            - containerPort: 80
