trigger:
  - master

variables:
  - group: docker
  # - name: DOCKER_BUILDKIT
  #   value: 1
  # - name: DOCKER_CLI_EXPERIMENTAL
  #   value: enabled
  - name: tag
    value: "0.1.$(Build.BuildId)"
  - name: cache_tag
    value: cache-master

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-20.04
    steps:
      # - script: sudo service docker restart

      - script: |
          helm template ./iac/helm-charts/refract-cms-web --set env=$(Build.SourceBranchName) --set tag=$(tag) --set dockerUsername=$(dockerUsername)
        displayName: Template helm chart

      - script: docker login -u $(dockerUsername) -p "$(dockerPassword)"

      - script: |
          docker version
          docker buildx ls
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name builder --driver docker-container --use
          docker buildx inspect --bootstrap
          docker buildx ls

      - script: |
          image=$(dockerUsername)/refract-cms-website
          docker buildx build \
            -t "${image}:$(tag)" \
            --platform linux/arm64,linux/amd64 \
            --push \
            --progress=plain \
            -f ./iac/dockerfiles/website.Dockerfile .
        displayName: "Build website"

  - job: Deploy
    dependsOn:
      - Build
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Default
      demands:
        - ARM_CLUSTER
    steps:
      - script: helm upgrade refract-cms-website --install --namespace refract-cms-$(Build.SourceBranchName) --create-namespace ./iac/helm-charts/refract-cms-web --set env=$(Build.SourceBranchName) --set tag=$(tag) --set dockerUsername=$(dockerUsername)
