name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn install
        run: |
          yarn

      - name: Yarn build
        run: |
          yarn build

      - name: Lerna publish
        if: github.ref == 'refs/heads/master'
        run: |
          npx lerna publish from-package
