name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "${HOME}/.deno/bin" >> $GITHUB_PATH
        name: "Install deno"
        if: github.event_name == 'pull_request'

      - run: |
          git fetch origin master
          git --no-pager diff origin/master HEAD

      - run: |
          deno run --allow-run --allow-env --allow-read ./check-version.ts
        name: "Check version"
        if: github.event_name == 'pull_request'

      - name: Yarn install
        run: |
          yarn

      - name: Yarn build
        run: |
          yarn build

      - name: Lerna publish
        if: github.ref == 'refs/heads/master'
        run: |
          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm config set access public
          npx lerna publish from-package --yes --contents pkg

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
