version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27022:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hqXzNv2f5YC45veW
    volumes:
      - mongovolume:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=hqXzNv2f5YC45veW
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hqXzNv2f5YC45veW
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    links:
      - mongo

volumes:
  mongovolume:
